export const TODO_ADD_REQUEST = 'TODO_ADD_REQUEST';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_FAIL = 'TODO_ADD_FAIL';
export const TODO_ADD_RESET = 'TODO_ADD_RESET';

export const TODO_GET_REQUEST = 'TODO_GET_REQUEST';
export const TODO_GET_SUCCESS = 'TODO_GET_SUCCESS';
export const TODO_GET_FAIL = 'TODO_GET_FAIL';
export const TODO_GET_RESET = 'TODO_GET_RESET';

export const TODO_GET_ALL_REQUEST = 'TODO_GET_ALL_REQUEST';
export const TODO_GET_ALL_SUCCESS = 'TODO_GET_ALL_SUCCESS';
export const TODO_GET_ALL_FAIL = 'TODO_GET_ALL_FAIL';
export const TODO_GET_ALL_RESET = 'TODO_GET_ALL_RESET';

export const TODO_EDIT_REQUEST = 'TODO_EDIT_REQUEST';
export const TODO_EDIT_SUCCESS = 'TODO_EDIT_SUCCESS';
export const TODO_EDIT_FAIL = 'TODO_EDIT_FAIL';
export const TODO_EDIT_RESET = 'TODO_EDIT_RESET';

export const TODO_MARK_AS_DONE_REQUEST = 'TODO_MARK_AS_DONE_REQUEST';
export const TODO_MARK_AS_DONE_SUCCESS = 'TODO_MARK_AS_DONE_SUCCESS';
export const TODO_MARK_AS_DONE_FAIL = 'TODO_MARK_AS_DONE_FAIL';
export const TODO_MARK_AS_DONE_RESET = 'TODO_MARK_AS_DONE_RESET';

export const TODO_DELETE_REQUEST = 'TODO_DELETE_REQUEST';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';
export const TODO_DELETE_RESET = 'TODO_DELETE_RESET';
